using Mentora.Domain.Common;
using Mentora.Domain.Entities.Auth;

namespace Mentora.Domain.Entities.Assessment
{
    /// <summary>
    /// AI-generated study plan per SRS 3.2 & Section 4
    /// Container entity for hierarchical study roadmap
    /// Integrates with Career Plans for holistic learning path
    /// </summary>
    public class AiStudyPlan : BaseEntity
    {
        /// <summary>
        /// User who owns this study plan
        /// </summary>
        public Guid UserId { get; set; }
        public User User { get; set; } = null!;

        /// <summary>
        /// Assessment attempt that generated this plan
        /// </summary>
        public Guid? AssessmentAttemptId { get; set; }
        public AssessmentAttempt? AssessmentAttempt { get; set; }

        /// <summary>
        /// Optional link to career plan for integration per SRS 5.1
        /// </summary>
        public Guid? CareerPlanId { get; set; }
        public CareerPlan? CareerPlan { get; set; }

        /// <summary>
        /// Plan title generated by AI
        /// </summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Executive summary of the study plan
        /// </summary>
        public string Summary { get; set; } = string.Empty;

        /// <summary>
        /// Target completion date based on user constraints
        /// </summary>
        public DateTime? TargetCompletionDate { get; set; }

        /// <summary>
        /// Estimated total hours required
        /// </summary>
        public int EstimatedHours { get; set; }

        /// <summary>
        /// Difficulty level of this plan
        /// </summary>
        public DifficultyLevel DifficultyLevel { get; set; }

        /// <summary>
        /// Current status of the study plan
        /// </summary>
        public StudyPlanStatus Status { get; set; } = StudyPlanStatus.Draft;

        /// <summary>
        /// Overall progress percentage (0-100) per SRS 5.2
        /// </summary>
        public int ProgressPercentage { get; set; } = 0;

        /// <summary>
        /// When the user started working on this plan
        /// </summary>
        public DateTime? StartedAt { get; set; }

        /// <summary>
        /// When the plan was completed
        /// </summary>
        public DateTime? CompletedAt { get; set; }

        /// <summary>
        /// Whether this is the active study plan for the user
        /// </summary>
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// AI model used for generation (e.g., "gpt-4", "gemini-pro")
        /// </summary>
        public string AiModel { get; set; } = string.Empty;

        /// <summary>
        /// AI request log reference for auditing per SRS 7.1
        /// </summary>
        public Guid? AiRequestLogId { get; set; }
        public AiRequestLog? AiRequestLog { get; set; }

        /// <summary>
        /// Raw AI response for debugging/analysis
        /// </summary>
        public string? RawAiResponseJson { get; set; }

        // Navigation properties
        public ICollection<StudyPlanStep> Steps { get; set; } = new List<StudyPlanStep>();
        public ICollection<StudyPlanSkill> RequiredSkills { get; set; } = new List<StudyPlanSkill>();
        public ICollection<StudyPlanResource> Resources { get; set; } = new List<StudyPlanResource>();
    }

    /// <summary>
    /// Difficulty level enum per SRS design
    /// </summary>
    public enum DifficultyLevel
    {
        Beginner = 0,
        Intermediate = 1,
        Advanced = 2,
        Expert = 3
    }

    /// <summary>
    /// Study plan status per SRS 3.2 & Section 4
    /// </summary>
    public enum StudyPlanStatus
    {
        /// <summary>
        /// Plan generated but not started
        /// </summary>
        Draft = 0,

        /// <summary>
        /// User is actively working on the plan
        /// </summary>
        Active = 1,

        /// <summary>
        /// Plan completed successfully
        /// </summary>
        Completed = 2,

        /// <summary>
        /// Plan archived by user
        /// </summary>
        Archived = 3,

        /// <summary>
        /// Plan paused/on hold
        /// </summary>
        Paused = 4,

        /// <summary>
        /// Plan cancelled/abandoned
        /// </summary>
        Cancelled = 5
    }
}
